(function(){
'use strict';
const MASTER_NAME='SADEER Y. MOHAMMED',DEFAULT_MASTER='5231636373',$=id=>document.getElementById(id);
const normalizeDigits=v=>String(v??'').replace(/[٠-٩]/g,c=>String(c.charCodeAt(0)-1632)).replace(/[۰-۹]/g,c=>String(c.charCodeAt(0)-1776)).replace(/\D/g,'');
function masterNumber(){try{if(typeof db!=='undefined'&&db&&db.settings){if(typeof db.settings.masterCardNumber!=='string'){db.settings.masterCardNumber=DEFAULT_MASTER;if(typeof persist==='function')persist()}return db.settings.masterCardNumber||DEFAULT_MASTER}}catch(e){}return DEFAULT_MASTER}
function updatePayment(){const n=$('masterPaymentNumber'),m=$('masterPaymentName');if(n)n.textContent=masterNumber()||'—';if(m)m.textContent=MASTER_NAME}
function ensurePayment(){if($('masterPayment')){updatePayment();return}const s=document.querySelector('.summary');if(!s)return;const e=document.createElement('section');e.id='masterPayment';e.className='master-payment';e.setAttribute('aria-label','بيانات الدفع بالماستر كارد');e.innerHTML='<div class="master-payment-title">يمكنك الدفع بالماستر كارد</div><div class="master-payment-row"><div class="master-card-mark" aria-label="MasterCard"><div class="master-circles" aria-hidden="true"><span class="master-circle red"></span><span class="master-circle orange"></span></div><span class="master-card-word">MasterCard</span></div><div class="master-payment-divider" aria-hidden="true"></div><div class="master-payment-data"><strong class="master-payment-name" id="masterPaymentName">SADEER Y. MOHAMMED</strong><span class="master-payment-number" id="masterPaymentNumber"></span></div></div>';s.insertAdjacentElement('afterend',e);updatePayment()}
function ensureSetting(){if($('setMasterNumber'))return;const f=$('settingsForm');if(!f)return;const a=$('setLogo')?.closest('.field');const w=document.createElement('div');w.className='field';w.id='masterNumberSetting';w.innerHTML='<label for="setMasterNumber">رقم حساب الماستر كارد</label><input id="setMasterNumber" type="text" inputmode="numeric" autocomplete="off" maxlength="30" placeholder="رقم حساب الماستر كارد">';if(a)a.before(w);else f.querySelector('.actions')?.before(w);$('setMasterNumber').value=masterNumber()}
function bindSettings(){ensureSetting();const o=$('openSettings');if(o&&!o.dataset.masterBound){o.dataset.masterBound='1';o.addEventListener('click',()=>setTimeout(()=>{ensureSetting();const i=$('setMasterNumber');if(i)i.value=masterNumber()},0))}const f=$('settingsForm');if(f&&!f.dataset.masterBound){f.dataset.masterBound='1';f.addEventListener('submit',ev=>{const i=$('setMasterNumber');if(!i)return;const d=normalizeDigits(i.value);if(d.length<6||d.length>30){ev.preventDefault();ev.stopImmediatePropagation();const er=$('settingsError');if(er)er.textContent='رقم حساب الماستر كارد يجب أن يحتوي من 6 إلى 30 رقمًا.';i.focus();return}i.value=d;try{if(typeof db!=='undefined'&&db&&db.settings)db.settings.masterCardNumber=d}catch(e){}updatePayment()},true)}}
function grow(el){if(!el||!el.matches('.expense-table .details-cell textarea'))return;el.style.height='auto';el.style.height=Math.max(58,el.scrollHeight)+'px'}function growAll(){document.querySelectorAll('.expense-table .details-cell textarea').forEach(grow)}document.addEventListener('input',e=>grow(e.target),true);
function clean(){const r=document.body;if(!r)return;const w=document.createTreeWalker(r,NodeFilter.SHOW_TEXT),a=[];while(w.nextNode())a.push(w.currentNode);a.forEach(n=>{const p=n.parentElement;if(!p||/^(SCRIPT|STYLE|TEXTAREA|INPUT)$/i.test(p.tagName))return;if(n.nodeValue&&n.nodeValue.includes('\\n'))n.nodeValue=n.nodeValue.replace(/\\n/g,' ')})}
function init(){document.documentElement.dataset.wasoolatVersion='29-navy-responsive-mastercard';const m=document.querySelector('meta[name="theme-color"]');if(m)m.content='#061a35';document.title='برنامج الوصولات — V29';ensurePayment();bindSettings();growAll();clean();new MutationObserver(()=>{ensurePayment();ensureSetting();growAll();clean()}).observe(document.body,{childList:true,subtree:true});window.addEventListener('orientationchange',()=>setTimeout(growAll,180));window.addEventListener('resize',()=>setTimeout(growAll,60),{passive:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();